// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('recorrido_inicial', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('recorrido_inicial', async function() {
    await driver.get("http://localhost:5173/home")
    await driver.manage().window().setRect({ width: 1838, height: 1048 })
    await driver.executeScript("window.scrollTo(0,596.75)")
    await driver.findElement(By.css(".\\1F90D")).click()
    await driver.findElement(By.css(".\\1F90D")).click()
    await driver.executeScript("window.scrollTo(0,596.75)")
    await driver.findElement(By.css(".lucide-user")).click()
    {
      const element = await driver.findElement(By.css(".lucide-user"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".dropdown-item:nth-child(2)")).click()
    await driver.executeScript("window.scrollTo(0,422.5833435058594)")
    await driver.findElement(By.css(".profile-info-buttons > .profile-btn")).click()
    await driver.findElement(By.css(".modal-input:nth-child(3)")).click()
    await driver.findElement(By.css(".modal-input:nth-child(3)")).sendKeys("felicia12")
    await driver.findElement(By.css(".modal-buttons > .profile-btn:nth-child(2)")).click()
    await driver.findElement(By.css(".profile-photo-buttons > .profile-btn:nth-child(1)")).click()
    await driver.findElement(By.css(".profile-btn:nth-child(2)")).click()
    assert(await driver.switchTo().alert().getText() == "¿Seguro que quieres eliminar tu foto?")
    await driver.switchTo().alert().accept()
    await driver.findElement(By.css(".profile-delete-account")).click()
    assert(await driver.switchTo().alert().getText() == "¿Seguro que quieres ELIMINAR TU CUENTA?")
    await driver.switchTo().alert().dismiss()
    await driver.findElement(By.linkText("Abrir")).click()
    await driver.findElement(By.css(".pack-container")).click()
    await driver.findElement(By.linkText("Colección")).click()
    {
      const element = await driver.findElement(By.linkText("Colección"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".is-flipped span")).click()
    {
      const element = await driver.findElement(By.css(".is-flipped span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".is-flipped span")).click()
    await driver.findElement(By.css(".is-flipped span")).click()
    await driver.findElement(By.css("select:nth-child(2)")).click()
    {
      const dropdown = await driver.findElement(By.css("select:nth-child(2)"))
      await dropdown.findElement(By.xpath("//option[. = 'Mega Evolution']")).click()
    }
    await driver.findElement(By.css("select:nth-child(2) > option:nth-child(2)")).click()
    await driver.findElement(By.css("select:nth-child(2)")).click()
    {
      const dropdown = await driver.findElement(By.css("select:nth-child(2)"))
      await dropdown.findElement(By.xpath("//option[. = 'Sets']")).click()
    }
    await driver.findElement(By.css("select:nth-child(2) > option:nth-child(1)")).click()
    await driver.findElement(By.css("select:nth-child(3)")).click()
    {
      const dropdown = await driver.findElement(By.css("select:nth-child(3)"))
      await dropdown.findElement(By.xpath("//option[. = 'Common']")).click()
    }
    await driver.findElement(By.css("select:nth-child(3) > option:nth-child(2)")).click()
    await driver.findElement(By.css("select:nth-child(4)")).click()
    {
      const dropdown = await driver.findElement(By.css("select:nth-child(4)"))
      await dropdown.findElement(By.xpath("//option[. = 'Darkness']")).click()
    }
    await driver.findElement(By.css("select:nth-child(4) > option:nth-child(2)")).click()
    await driver.findElement(By.css("select:nth-child(3)")).click()
    {
      const dropdown = await driver.findElement(By.css("select:nth-child(3)"))
      await dropdown.findElement(By.xpath("//option[. = 'Rareza']")).click()
    }
    await driver.findElement(By.css("select:nth-child(3) > option:nth-child(1)")).click()
    await driver.findElement(By.css("select:nth-child(3)")).click()
    await driver.findElement(By.css("select:nth-child(3) > option:nth-child(1)")).click()
    await driver.findElement(By.css("select:nth-child(4)")).click()
    {
      const dropdown = await driver.findElement(By.css("select:nth-child(4)"))
      await dropdown.findElement(By.xpath("//option[. = 'Tipo']")).click()
    }
    await driver.findElement(By.css("select:nth-child(4) > option:nth-child(1)")).click()
    await driver.findElement(By.css("select:nth-child(5)")).click()
    {
      const dropdown = await driver.findElement(By.css("select:nth-child(5)"))
      await dropdown.findElement(By.xpath("//option[. = 'Rareza']")).click()
    }
    await driver.findElement(By.css("select:nth-child(5) > option:nth-child(3)")).click()
    await driver.findElement(By.css(".CollectionButton:nth-child(6)")).click()
    await driver.findElement(By.css(".CollectionButton:nth-child(6)")).click()
    await driver.findElement(By.css(".is-flipped span")).click()
    {
      const element = await driver.findElement(By.css(".is-flipped span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Abrir")).click()
    {
      const element = await driver.findElement(By.linkText("Abrir"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".set-button:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.css(".set-button:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".pack-container")).click()
    await driver.findElement(By.linkText("Colección")).click()
    {
      const element = await driver.findElement(By.linkText("Colección"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".CollectionButton:nth-child(3)")).click()
    await driver.findElement(By.css(".discover-pagination > .CollectionButton:nth-child(1)")).click()
    await driver.findElement(By.css(".collection-filters > .header-search")).click()
    await driver.findElement(By.css(".relative > .relative")).click()
    await driver.findElement(By.css(".relative > .relative")).click()
    await driver.findElement(By.css(".lucide-globe")).click()
    {
      const element = await driver.findElement(By.css(".lucide-globe"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".text-gray-700")).click()
    await driver.findElement(By.linkText("Open")).click()
    await driver.findElement(By.css(".relative > .CollectionButton")).click()
    await driver.findElement(By.css(".header-logo")).click()
    {
      const element = await driver.findElement(By.linkText("Collection"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.executeScript("window.scrollTo(0,550)")
    await driver.findElement(By.css(".lucide-moon")).click()
    await driver.findElement(By.css(".lucide-sun")).click()
    await driver.findElement(By.css(".lucide-user")).click()
    await driver.findElement(By.css(".dropdown-item:nth-child(2)")).click()
    await driver.findElement(By.css(".lucide-user")).click()
    {
      const element = await driver.findElement(By.css(".lucide-user"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".dropdown-item:nth-child(1)")).click()
    await driver.findElement(By.css(".input-box")).click()
    await driver.findElement(By.css(".input-box")).sendKeys("pepe")
    await driver.findElement(By.css(".btn-blue")).click()
    {
      const element = await driver.findElement(By.css(".btn-blue"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".btn-blue-small")).click()
    {
      const element = await driver.findElement(By.css(".btn-blue-small"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".friend-button")).click()
    {
      const element = await driver.findElement(By.css(".friend-button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".input-box:nth-child(1)")).click()
    await driver.findElement(By.css(".input-box:nth-child(1)")).sendKeys("hola")
    await driver.findElement(By.css(".btn-send")).click()
    {
      const element = await driver.findElement(By.css(".btn-send"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("circle:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.css("circle:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".dropdown-item:nth-child(2)")).click()
    await driver.findElement(By.css(".profile-delete-account")).click()
    assert(await driver.switchTo().alert().getText() == "Are you sure you want to DELETE YOUR ACCOUNT?")
    await driver.switchTo().alert().accept()
  })
})
